import cover from '/public/cover-project.png'
import hero from '/public/hero-project.jpg'
import oji from '/public/miftah-fauzy.jpeg'

export const dataProject = [
    {
        "id": 1,
        "title": "Rumah Kepemimpinan",
        "description": "Program pelatihan kepemimpinan untuk mahasiswa",
        "type": "Brand Dev",
        "asset1": oji,
        "asset2": oji,
        "asset3": oji,
        "asset4": oji,
        "asset5": oji,
        "asset6": oji,
        "cover": cover,
        "hero": hero
    },
    {
        "id": 2,
        "title": "Startup Digital",
        "description": "Mentoring untuk pengembangan startup",
        "type": "Graphic & Motion",
        "asset1": oji,
        "asset2": oji,
        "asset3": oji,
        "asset4": oji,
        "asset5": oji,
        "asset6": oji,
        "cover": cover,
        "hero": hero
    },
    {
        "id": 3,
        "title": "Pelatihan Desain Grafis",
        "description": "Kursus intensif desain grafis",
        "type": "Graphic & Motion",
        "asset1": oji,
        "asset2": oji,
        "asset3": oji,
        "asset4": oji,
        "asset5": oji,
        "asset6": oji,
        "cover": cover,
        "hero": hero
    },
    {
        "id": 4,
        "title": "Web Development Bootcamp",
        "description": "Pelatihan intensif pengembangan web",
        "type": "Landing Page",
        "asset1": oji,
        "asset2": oji,
        "asset3": oji,
        "asset4": oji,
        "asset5": oji,
        "asset6": oji,
        "cover": cover,
        "hero": hero
    },
    {
        "id": 5,
        "title": "Fotografi Pemula",
        "description": "Belajar dasar-dasar fotografi",
        "type": "Video & Photo",
        "asset1": oji,
        "asset2": oji,
        "asset3": oji,
        "asset4": oji,
        "asset5": oji,
        "asset6": oji,
        "cover": cover,
        "hero": hero
    },
    {
        "id": 6,
        "title": "Kursus Masak Online",
        "description": "Belajar memasak berbagai masakan",
        "type": "Brand Dev",
        "asset1": oji,
        "asset2": oji,
        "asset3": oji,
        "asset4": oji,
        "asset5": oji,
        "asset6": oji,
        "cover": cover,
        "hero": hero
    },
    {
        "id": 7,
        "title": "Pelatihan Yoga",
        "description": "Kelas yoga untuk pemula dan lanjutan",
        "type": "Video & Photo",
        "asset1": oji,
        "asset2": oji,
        "asset3": oji,
        "asset4": oji,
        "asset5": oji,
        "asset6": oji,
        "cover": cover,
        "hero": hero
    },
    {
        "id": 8,
        "title": "Pelatihan Musik Online",
        "description": "Belajar bermain alat musik",
        "type": "Brand Dev",
        "asset1": oji,
        "asset2": oji,
        "asset3": oji,
        "asset4": oji,
        "asset5": oji,
        "asset6": oji,
        "cover": cover,
        "hero": hero
    },
    {
        "id": 9,
        "title": "Pelatihan Digital Marketing",
        "description": "Strategi pemasaran digital untuk bisnis",
        "type": "Landing Page",
        "asset1": oji,
        "asset2": oji,
        "asset3": oji,
        "asset4": oji,
        "asset5": oji,
        "asset6": oji,
        "cover": cover,
        "hero": hero
    },
    {
        "id": 10,
        "title": "Kursus Bahasa Asing",
        "description": "Belajar bahasa asing secara online",
        "type": "Graphic & Motion",
        "asset1": oji,
        "asset2": oji,
        "asset3": oji,
        "asset4": oji,
        "asset5": oji,
        "asset6": oji,
        "cover": cover,
        "hero": hero
    },
    {
        "id": 11,
        "title": "Pelatihan Public Speaking",
        "description": "Keterampilan berbicara di depan umum",
        "type": "Brand Dev",
        "asset1": oji,
        "asset2": oji,
        "asset3": oji,
        "asset4": oji,
        "asset5": oji,
        "asset6": oji,
        "cover": cover,
        "hero": hero
    },
    {
        "id": 12,
        "title": "Workshop Seni Lukis",
        "description": "Pelatihan seni lukis untuk pemula",
        "type": "Graphic & Motion",
        "asset1": oji,
        "asset2": oji,
        "asset3": oji,
        "asset4": oji,
        "asset5": oji,
        "asset6": oji,
        "cover": cover,
        "hero": hero
    },
    {
        "id": 13,
        "title": "Kursus Fotografi Alam",
        "description": "Belajar fotografi alam dan lanskap",
        "type": "Video & Photo",
        "asset1": oji,
        "asset2": oji,
        "asset3": oji,
        "asset4": oji,
        "asset5": oji,
        "asset6": oji,
        "cover": cover,
        "hero": hero
    },
    {
        "id": 14,
        "title": "Pelatihan Kesehatan Mental",
        "description": "Program dukungan kesehatan mental",
        "type": "Brand Dev",
        "asset1": oji,
        "asset2": oji,
        "asset3": oji,
        "asset4": oji,
        "asset5": oji,
        "asset6": oji,
        "cover": cover,
        "hero": hero
    },
    {
        "id": 15,
        "title": "Pelatihan Menulis Kreatif",
        "description": "Kursus menulis kreatif untuk penulis pemula",
        "type": "Landing Page",
        "asset1": oji,
        "asset2": oji,
        "asset3": oji,
        "asset4": oji,
        "asset5": oji,
        "asset6": oji,
        "cover": cover,
        "hero": hero
    },
    {
        "id": 16,
        "title": "Pelatihan Coding untuk Anak",
        "description": "Belajar coding untuk anak-anak",
        "type": "Landing Page",
        "asset1": oji,
        "asset2": oji,
        "asset3": oji,
        "asset4": oji,
        "asset5": oji,
        "asset6": oji,
        "cover": cover,
        "hero": hero
    },
    {
        "id": 17,
        "title": "Kursus Olahraga Online",
        "description": "Latihan olahraga yang bisa diikuti dari rumah",
        "type": "Video & Photo",
        "asset1": oji,
        "asset2": oji,
        "asset3": oji,
        "asset4": oji,
        "asset5": oji,
        "asset6": oji,
        "cover": cover,
        "hero": hero
    },
    {
        "id": 18,
        "title": "Pelatihan Desain UI/UX",
        "description": "Kursus desain antarmuka pengguna",
        "type": "Graphic & Motion",
        "asset1": oji,
        "asset2": oji,
        "asset3": oji,
        "asset4": oji,
        "asset5": oji,
        "asset6": oji,
        "cover": cover,
        "hero": hero
    },
    {
        "id": 19,
        "title": "Kursus Pemrograman Mobile",
        "description": "Pelatihan pengembangan aplikasi mobile",
        "type": "Landing Page",
        "asset1": oji,
        "asset2": oji,
        "asset3": oji,
        "asset4": oji,
        "asset5": oji,
        "asset6": oji,
        "cover": cover,
        "hero": hero
    },
    {
        "id": 20,
        "title": "Pelatihan Animasi 2D",
        "description": "Belajar membuat animasi 2D",
        "type": "Graphic & Motion",
        "asset1": oji,
        "asset2": oji,
        "asset3": oji,
        "asset4": oji,
        "asset5": oji,
        "asset6": oji,
        "cover": cover,
        "hero": hero
    }
]